name: CI/CD Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [main, develop, Setting/#16/https]

# 환경설정
env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/react-auto-deploy
  VERSION: ${{ github.sha }}
  NAME: go_cicd

jobs:
  # 빌드 Job
  build:
  runs-on: ubuntu-latest
  steps:
    # 제공하는 checkout 액션을 이용해 리포지토리 가져오기
    - uses: actions/checkout@v3

    - run: pwd
    - run: ls -al

    # 노드 액션을 통해 npm 명령어 사용
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
  # 배포 Job
  # deploy:
  #   needs: build # build 후에 실행되도록 정의
  #   name: Deploy
  #   runs-on: [self-hosted, label-go] # AWS ./configure에서 사용할 label명
  #   steps:
  #     - name: Login to ghcr
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor  }}
  #         password: ${{ github.actor == 'bluetree7878' && secrets.bluetree7878_GHCR_TOKEN || secrets.rhehfl_ghcr_token }}
  #     # 3000 -> 80 포트로 수행하도록 지정
  #     - name: Docker run
  #       run: |
  #         docker compose down
  #         docker compose up -d
